//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int eId { get; set; }
        public string eName { get; set; }
        public string eUserName { get; set; }
        public string eEmail { get; set; }
        public string eGender { get; set; }
        public string ePassword { get; set; }
    }
}
