//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Donor
    {
        public int dnId { get; set; }
        public string dnName { get; set; }
        public string dnUserName { get; set; }
        public string dnEmail { get; set; }
        public string dnGender { get; set; }
        public string dnPassword { get; set; }
    }
}
