//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fundProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class raiser
    {
        public int raiserId { get; set; }
        public Nullable<int> uId { get; set; }
        [Required(ErrorMessage ="Required")]
        public string uName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string uraiseAmount { get; set; }
        [Required(ErrorMessage = "Required")]
        public string uDescription { get; set; }
        [Required(ErrorMessage = "Required")]
        public string uAddress { get; set; }
        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string uEmail { get; set; }
        [Required(ErrorMessage = "Required")]
        [MinLength(11,ErrorMessage ="Mobile N0 should be 11 digits")]
        public string uMobile { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Date { get; set; }
        [Required(ErrorMessage = "Required")]
        public byte[] image { get; set; }
        public string status { get; set; }
    
        public virtual users1 users1 { get; set; }
    }
}
