//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fundProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class users1
    {
        public users1()
        {
            this.raisers = new HashSet<raiser>();
        }
    
        public int uId { get; set; }

        [Required(ErrorMessage ="Name is Required")]
        public string uName { get; set; }

        [Required(ErrorMessage = "User Name is Required")]
        public string uUserName { get; set; }

        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string uEmail { get; set; }

        [Required(ErrorMessage = "Required")]
        public string uGender { get; set; }

        [Required(ErrorMessage = "Password is Required")]
        public string uPassword { get; set; }
    
        public virtual ICollection<raiser> raisers { get; set; }
    }
}
