//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donor.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_donation
    {
        public int UserId { get; set; }
        [required]
        public string UserName { get; set; }
        [required]
        public Nullable<int> Ammount { get; set; }
    }
}
