//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FundEntities : DbContext
    {
        public FundEntities()
            : base("name=FundEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<emp> emps { get; set; }
        public DbSet<tbl_donation> tbl_donation { get; set; }
        public DbSet<Tbl_Donor> Tbl_Donor { get; set; }
        public DbSet<users1> users1 { get; set; }
    }
}
